# ============================================== #
# User Management Portal [backend] Configuration #
# ============================================== #

jwt-config:
  secret: gw3Gh6#eMT7rRk!-369e$0f7-SqCfmxNWrz@PF4K

spring:
  application:
    name: USER-MANAGEMENT-PORTAL
  datasource:
    url: jdbc:mysql://localhost:3306/user_mgmt_portal
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    username: jbsoft247@gmail.com
    password: wtjqqgotdqshpvwz

server:
  port: 8881

